name: Libredirect Release

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          persist-credentials: 'false'
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Build artifacts
        run: |
          npm run ejs
          npm run build
      - name: Hash artifacts
        run: sha256sum artifacts/*/*
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: artifacts
          path: artifacts/
          retention-days: 1
  release:
    name: Release on GitHub
    runs-on: ubuntu-22.04
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - name: Get release information
        id: release_info
        run: |
          echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: artifacts/
      - name: Hash artifacts
        run: sha256sum artifacts/*/*
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release_info.outputs.TAG }}
          name: ${{ steps.release_info.outputs.TAG }}
          body: |
            Download and install the extension from the [extension store](https://github.com/libredirect/libredirect#readme) of your browser.
          files: artifacts/*/*
          fail_on_unmatched_files: true
          draft: true
